name: CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/uptime-checker:latest
          build-args: |
            GLOBALPING_API_KEY=${{ secrets.GLOBALPING_API_KEY }}
            GLOBALPING_API_KEY2=${{ secrets.GLOBALPING_API_KEY2 }}
             GLOBALPING_API_KEY3=${{ secrets.GLOBALPING_API_KEY3 }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Clone the repository
            git clone https://github.com/${{ github.repository }}.git uptime-checker || true
            cd uptime-checker
            git pull
            # Install docker-compose
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            # Create .env file
            echo "GLOBALPING_API_KEY=${{ secrets.GLOBALPING_API_KEY }}" > .env
            echo "GLOBALPING_API_KEY3=${{ secrets.GLOBALPING_API_KEY3 }}" >> .env
            echo "GLOBALPING_API_KEY2=${{ secrets.GLOBALPING_API_KEY2 }}" >> .env
            # Stop and disable system nginx if it exists
            sudo systemctl stop nginx || true
            sudo systemctl disable nginx || true
            # Stop and remove all containers
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            # Pull the latest image
            docker-compose pull
            # Run the new container
            docker-compose up -d --build